// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroCreator.Services;

namespace SuperHeroCreator.Migrations
{
    [DbContext(typeof(SuperHeroesDbContext))]
    [Migration("20190726201338_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperHeroCreator.Models.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlterEgo");

                    b.Property<string>("CatchPhrase");

                    b.Property<string>("Name");

                    b.Property<string>("PrimarySuperHeroAbility");

                    b.Property<string>("SecondarySuperHeroAbility");

                    b.HasKey("Id");

                    b.ToTable("SuperHero");
                });
#pragma warning restore 612, 618
        }
    }
}
